excluded:
  - Pods
  - Carthage
  - Carthage/facebook-objc-sdk/samples
  - Carthage/facebook-objc-sdk/vendor

cyclomatic_complexity: 11
identifier_name:
  excluded:
    - ok
    - y
    - x
    - id
indentation: 2
large_tuple: 3
line_length: 120
nesting:
  type_level: 2
private_outlet:
  allow_private_set: true

disabled_rules:
  - conditional_returns_on_newline
  - discouraged_object_literal
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - no_extension_access_modifier
  - number_separator
  - prefixed_toplevel_constant
  - switch_case_on_newline
  - no_fallthrough_only

opt_in_rules:
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - dynamic_inline
  - empty_count
  - empty_string
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_length
  - file_name
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicit_return
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - notification_center_detachment
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - strict_fileprivate
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message
  - yoda_condition
  - discouraged_optional_boolean
  - function_default_parameter_at_end
  - todo